Repository SAP/xsk, pull requests merged in 2021-08, with the labels that each got.

#359 $.web API enhancements
  modules/api/api-xsjs/src/main/resources/xsk/web/web.js
  modules/engines/engine-xsjs/src/test/resources/test/xsk/request/request.xsjs
Labels: enhancement

#377 Refactored the $.net unit test
  modules/engines/engine-xsjs/src/test/java/com/sap/xsk/engine/api/test/XSKApiSuiteTest.java
  modules/engines/engine-xsjs/src/test/resources/test/xsk/net/net.xsjs
Labels: API

#376 Parser errors now pass through ProblemsFacade
  modules/engines/engine-commons/pom.xml
  modules/engines/engine-commons/src/main/java/com/sap/xsk/utils/XSKCommonsUtils.java
  modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/parser/XSKDataStructureParser.java
  modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/parser/hdbschema/XSKSchemaParser.java
  modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/parser/hdbsequence/XSKHDBSequenceParser.java
  modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/parser/hdbtable/XSKTableParser.java
  modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/parser/hdbview/XSKViewParser.java
  modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/service/parser/IXSKCoreParserService.java
  modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/service/parser/XSKCoreParserService.java
  modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/synchronizer/XSKDataStructuresSynchronizer.java
  modules/engines/engine-hdbti/src/main/java/com/sap/xsk/hdbti/api/IXSKHDBTIProcessor.java
  modules/engines/engine-hdbti/src/main/java/com/sap/xsk/hdbti/api/IXSKTableImportArtifactFactory.java
  modules/engines/engine-hdbti/src/main/java/com/sap/xsk/hdbti/api/IXSKTableImportParser.java
  modules/engines/engine-hdbti/src/main/java/com/sap/xsk/hdbti/processors/XSKHDBTIProcessor.java
  modules/engines/engine-hdbti/src/main/java/com/sap/xsk/hdbti/service/XSKTableImportParser.java
  modules/engines/engine-hdbti/src/main/java/com/sap/xsk/hdbti/synchronizer/XSKTableImportSynchronizer.java
  modules/engines/engine-hdbti/src/main/java/com/sap/xsk/hdbti/transformer/XSKTableImportArtifactFactory.java
  modules/engines/engine-hdbti/src/test/java/com/sap/xsk/hdbti/processors/XSKHDBTIProcessorTest.java
  modules/engines/engine-xsodata/src/main/java/com/sap/xsk/xsodata/ds/service/XSKODataParser.java
  modules/engines/engine-xsodata/src/test/java/XSKOdataParserTest.java
  modules/parsers/parser-all/pom.xml
  modules/parsers/parser-commons/pom.xml
  modules/parsers/parser-commons/src/main/java/com/sap/xsk/parser/models/BaseParserErrorsModel.java
  modules/parsers/parser-commons/src/main/java/com/sap/xsk/parser/utils/ParserConstants.java
  modules/parsers/parser-hdbschema/pom.xml
  modules/parsers/parser-hdbschema/src/main/java/com/sap/xsk/parser/hdbschema/custom/XSKHDBSCHEMASyntaxErrorListener.java
  modules/parsers/parser-hdbsequence/pom.xml
  modules/parsers/parser-hdbsequence/src/main/java/com/sap/xsk/parser/hdbsequence/custom/XSKHDBSEQUENCESyntaxErrorListener.java
  modules/parsers/parser-hdbtable/pom.xml
  modules/parsers/parser-hdbtable/src/main/java/com/sap/xsk/parser/hdbtable/custom/XSKHDBTABLESyntaxErrorListener.java
  modules/parsers/parser-hdbti/pom.xml
  modules/parsers/parser-hdbti/src/main/java/com/sap/xsk/parser/hdbti/custom/IXSKHDBTIParser.java
  modules/parsers/parser-hdbti/src/main/java/com/sap/xsk/parser/hdbti/custom/XSKHDBTIParser.java
  modules/parsers/parser-hdbti/src/main/java/com/sap/xsk/parser/hdbti/custom/XSKHDBTISyntaxErrorListener.java
  modules/parsers/parser-hdbti/src/test/java/com/sap/xsk/parser/hdbti/custom/XSKHDBTIParserTest.java
  modules/parsers/parser-hdbview/pom.xml
  modules/parsers/parser-hdbview/src/main/java/com/sap/xsk/parser/hdbview/custom/XSKHDBVIEWErrorListener.java
  modules/parsers/parser-xsodata/pom.xml
  modules/parsers/parser-xsodata/src/main/java/com/sap/xsk/parser/xsodata/custom/XSKHDBXSODATASyntaxErrorListener.java
  modules/parsers/pom.xml
Labels: customer
