Repository SAP/xsk, pull requests merged in 2022-02, with the labels that each got.

#1166 Add support for 'NCHAR' type of preparedStatement parameter
  modules/api/api-xsjs/src/main/resources/META-INF/dirigible/xsk/hdb/hdb.js
Labels: customer

#1194 Add publicsynonym plugin to created/modified HDI container
  modules/engines/engine-hdi/src/main/java/com/sap/xsk/hdb/ds/processors/hdi/XSKConfigureLibrariesProcessor.java
  modules/engines/engine-hdi/src/main/java/com/sap/xsk/hdb/ds/processors/hdi/XSKHDIContainerCreateProcessor.java
  modules/engines/engine-hdi/src/main/java/com/sap/xsk/hdb/ds/processors/hdi/XSKHDIContainerDropProcessor.java
  modules/engines/engine-hdi/src/test/java/com/sap/xsk/hdb/ds/processors/hdi/XSKConfigureLibrariesProcessorTest.java
Labels: bug, priority-high, customer

#1244 Improve HDI container creation - User Authorizations
  modules/engines/engine-hdi/src/main/java/com/sap/xsk/hdb/ds/processors/hdi/XSKGrantPrivilegesContainerTargetSchemaProcessor.java
  modules/engines/engine-hdi/src/main/java/com/sap/xsk/hdb/ds/processors/hdi/XSKHDIContainerCreateProcessor.java
Labels: bug, Improvement

#1304 new sorting and depleting algorithm for hdb
  integration-tests/engine-hdb/src/test/java/com/sap/xsk/hdb/ds/itest/AbstractXSKHDBITTest.java
  integration-tests/engine-hdb/src/test/java/com/sap/xsk/hdb/ds/itest/hdbtable/XSKHDBTableParserHanaITTest.java
  integration-tests/engine-hdb/src/test/java/com/sap/xsk/hdb/ds/itest/module/XSKHDBTestModule.java
  modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/api/IXSKDataStructureModel.java
  modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/artefacts/HDBScalarFunctionSynchronizationArtefactType.java
  modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/facade/IXSKHDBCoreSynchronizationFacade.java
  modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/facade/XSKHDBCoreFacade.java
  modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/facade/XSKHDBCoreSynchronizationFacade.java
  modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/facade/XSKTopologyDataStructureModelEnum.java
  modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/facade/XSKTopologyDataStructureModelWrapper.java
  modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/model/hdbscalarfunction/XSKDataStructureHDBScalarFunctionModel.java
  modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/module/XSKHDBModule.java
  modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/parser/hdbscalarfunction/XSKHDBScalarFunctionParser.java
  modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/processors/AbstractXSKProcessor.java
  modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/service/manager/XSKEntityManagerService.java
  modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/service/manager/XSKHDBSequenceManagerService.java
  modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/service/manager/XSKProceduresManagerService.java
  modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/service/manager/XSKScalarFunctionManagerService.java
  modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/service/manager/XSKSchemaManagerService.java
  modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/service/manager/XSKTableFunctionManagerService.java
  modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/service/manager/XSKTableManagerService.java
  modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/service/manager/XSKTableTypeManagerService.java
  modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/service/manager/XSKViewManagerService.java
  modules/engines/engine-hdb/src/main/java/com/sap/xsk/hdb/ds/synchronizer/XSKDataStructuresSynchronizer.java
Labels: core, priority-high, effort-high, database, customer, WIP, Improvement, _Tantel_
