Repository SAP/xsk, pull requests merged in 2022-01, with the labels that each got.

#941 Fix XSKODataUtilsTest failing tests with new dirigible version
  modules/engines/engine-xsodata/src/test/java/XSKODataUtilsTest.java
  pom.xml
Labels: dependencies, core, priority-high, blocker

#960 User schema search for DB artefacts
  modules/engines/engine-commons/src/main/java/com/sap/xsk/utils/XSKCommonsDBUtils.java
  modules/engines/engine-xsodata/src/main/java/com/sap/xsk/xsodata/ds/model/XSKDBArtifactModel.java
  modules/engines/engine-xsodata/src/main/java/com/sap/xsk/xsodata/ds/service/XSKOData2ODataXTransformer.java
  modules/engines/engine-xsodata/src/main/java/com/sap/xsk/xsodata/ds/service/XSKODataParser.java
  modules/engines/engine-xsodata/src/main/java/com/sap/xsk/xsodata/ds/service/XSKTableMetadataProvider.java
  modules/engines/engine-xsodata/src/main/java/com/sap/xsk/xsodata/utils/XSKODataUtils.java
  modules/engines/engine-xsodata/src/test/java/XSKOdataParserTest.java
  modules/engines/engine-xsodata/src/test/java/com/sap/xsk/xsodata/utils/XSKODataUtilsTest.java
  pom.xml
Labels: priority-high, customer

#1020 Modifications on migrated files
  modules/engines/engine-commons/src/main/java/com/sap/xsk/utils/XSKCommonsConstants.java
  modules/engines/engine-core/src/main/java/com/sap/xsk/modificators/XSKProjectFilesModificator.java
  modules/engines/engine-core/src/main/java/com/sap/xsk/modificators/XSKProjectMigrationInterceptor.java
  modules/engines/engine-core/src/main/resources/META-INF/modificators/xslt/analyticprivilege.xslt
  modules/engines/engine-core/src/test/java/com/sap/xsk/modificators/XSKProjectFilesModificatorTest.java
  modules/engines/engine-core/src/test/resources/META-INF/modificators/expected-results/testEmptyModelUri.analyticprivilege
  modules/engines/engine-core/src/test/resources/META-INF/modificators/expected-results/testEmptyWhereSql.analyticprivilege
  modules/engines/engine-core/src/test/resources/META-INF/modificators/expected-results/testNoModelUri.analyticprivilege
  modules/engines/engine-core/src/test/resources/META-INF/modificators/expected-results/testNoSessionUser.analyticprivilege
  modules/engines/engine-core/src/test/resources/META-INF/modificators/expected-results/testNoSessionUser.hdbanalyticprivilege
  modules/engines/engine-core/src/test/resources/META-INF/modificators/expected-results/testNoWhereSql.analyticprivilege
  modules/engines/engine-core/src/test/resources/META-INF/modificators/expected-results/testSuccessful.analyticprivilege
  modules/engines/engine-core/src/test/resources/META-INF/modificators/expected-results/testSuccessful.hdbanalyticprivilege
  modules/engines/engine-core/src/test/resources/META-INF/modificators/expected-results/testSuccessful.hdbprocedure
  modules/engines/engine-core/src/test/resources/META-INF/modificators/expected-results/testSuccessful.hdbtablefunction
  modules/engines/engine-core/src/test/resources/META-INF/modificators/expected-results/testSuccessful.xsjs
  modules/engines/engine-core/src/test/resources/META-INF/modificators/expected-results/testSuccessful.xsjslib
  modules/engines/engine-core/src/test/resources/META-INF/modificators/files-to-modify/testEmptyModelUri.analyticprivilege
  modules/engines/engine-core/src/test/resources/META-INF/modificators/files-to-modify/testEmptyWhereSql.analyticprivilege
  modules/engines/engine-core/src/test/resources/META-INF/modificators/files-to-modify/testNoModelUri.analyticprivilege
  modules/engines/engine-core/src/test/resources/META-INF/modificators/files-to-modify/testNoSessionUser.analyticprivilege
  modules/engines/engine-core/src/test/resources/META-INF/modificators/files-to-modify/testNoSessionUser.hdbanalyticprivilege
  modules/engines/engine-core/src/test/resources/META-INF/modificators/files-to-modify/testNoSessionUser.hdbprocedure
  modules/engines/engine-core/src/test/resources/META-INF/modificators/files-to-modify/testNoSessionUser.hdbtablefunction
  modules/engines/engine-core/src/test/resources/META-INF/modificators/files-to-modify/testNoSessionUser.xsjs
  modules/engines/engine-core/src/test/resources/META-INF/modificators/files-to-modify/testNoSessionUser.xsjslib
  modules/engines/engine-core/src/test/resources/META-INF/modificators/files-to-modify/testNoWhereSql.analyticprivilege
  modules/engines/engine-core/src/test/resources/META-INF/modificators/files-to-modify/testSuccessful.analyticprivilege
  modules/engines/engine-core/src/test/resources/META-INF/modificators/files-to-modify/testSuccessful.hdbanalyticprivilege
  modules/engines/engine-core/src/test/resources/META-INF/modificators/files-to-modify/testSuccessful.hdbprocedure
  modules/engines/engine-core/src/test/resources/META-INF/modificators/files-to-modify/testSuccessful.hdbtablefunction
  modules/engines/engine-core/src/test/resources/META-INF/modificators/files-to-modify/testSuccessful.xsjs
  modules/engines/engine-core/src/test/resources/META-INF/modificators/files-to-modify/testSuccessful.xsjslib
  modules/engines/engine-core/src/test/resources/META-INF/modificators/files-to-modify/testUnsupported.txt
  modules/engines/engine-core/src/test/resources/META-INF/modificators/files-to-modify/testWrongFormat.analyticprivilege
Labels: customer
